services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: ""
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/fleet_manager_development
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fleet_manager_development
    ports:
      - "5432:5432"

volumes:
  bundle:
  postgres_data: